### PR TITLE
wpewebkit backlog

### PR DESCRIPTION
**Pull request by philn**
commit a92a57acd5a47809d69000cd10e3a9032dceeeea (HEAD -> wpewebkit-backlog, phil/wpewebkit-backlog, master)
Author: Philippe Normand <philn@igalia.com>
Date:   Fri Jan 18 16:52:15 2019 +0000

    wpewebkit: New build options for experimental features, service workers and webgl2

commit 4773050848b32824796df5e3244e8812f74f41d2
Author: Philippe Normand <philn@igalia.com>
Date:   Fri Jan 18 16:51:26 2019 +0000

    wpewebkit: Enable Ninja, ccache and Release build configuration

commit 58f2ae65532b141d85cc19ee3ce42dcc8b0cb096
Author: Philippe Normand <philn@igalia.com>
Date:   Thu Jan 10 12:56:55 2019 +0000

    wpewebkit: Bump to 2.22.3

commit b08d66e39e77d9862149849867eb56f96807a4e5
Author: Philippe Normand <philn@igalia.com>
Date:   Tue Jan 8 09:58:56 2019 +0000

    wpewebkit: QtWPE build support

### CODE REVIEW

**Comment by psaavedra** [comment]
https://gitlab.com/saavedra.pablo/meta-perf-browser/pipelines/43944695

**Comment by psaavedra** [comment]
```
URI: http://code.qt.io/yocto/meta-qt5.git
branch: 5.12
revision: HEAD
```

**Comment by philn** [comment]
> https://gitlab.com/saavedra.pablo/meta-perf-browser/-/jobs/148008463

> New layer is now required.

As mentioned in the README :)

**Comment by psaavedra** [comment]
[FAIL] WPE 2.20 recipe is now broken: https://gitlab.com/saavedra.pablo/meta-perf-browser/-/jobs/148013994

**Comment by philn** [comment]
The log is truncated. What's the error?

**Comment by psaavedra** [comment]
> The log is truncated. What's the error?

The error is the following:

```
In file included from /home/igalia/psaavedra/yocto-wandboard-wpe/builds/wandboard-mesa-wpe-2.20/tmp/work/armv7at2hf-neon-imx-poky-linux-gnueabi/wpewebkit/2.20.2-r0/wpewebkit-2.20.2/Source/WebKit/StorageProcess/ServiceWorker/WebSWOriginStore.cpp:31:
DerivedSources/WebKit/WebSWClientConnectionMessages.h:31:10: fatal error: WebCore/DocumentIdentifier.h: No such file or directory
 #include <WebCore/DocumentIdentifier.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

But ...

```
find ../wpewebkit-2.20.2/ -name DocumentIdentifier.h
../wpewebkit-2.20.2/Source/WebCore/dom/DocumentIdentifier.h
```

**Comment by psaavedra** [comment]
> > The log is truncated. What's the error?
> 
> The error is the following:
> 
> ```
> In file included from /home/igalia/psaavedra/yocto-wandboard-wpe/builds/wandboard-mesa-wpe-2.20/tmp/work/armv7at2hf-neon-imx-poky-linux-gnueabi/wpewebkit/2.20.2-r0/wpewebkit-2.20.2/Source/WebKit/StorageProcess/ServiceWorker/WebSWOriginStore.cpp:31:
> DerivedSources/WebKit/WebSWClientConnectionMessages.h:31:10: fatal error: WebCore/DocumentIdentifier.h: No such file or directory
>  #include <WebCore/DocumentIdentifier.h>
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> But ...
> 
> ```
> find ../wpewebkit-2.20.2/ -name DocumentIdentifier.h
> ../wpewebkit-2.20.2/Source/WebCore/dom/DocumentIdentifier.h
> ```

OK. Maybe the reason is the activation by default of the experimental features: https://github.com/Igalia/meta-webkit/pull/62/files#diff-1cafee4b8e603d46c49b57c95ad28152R26

**Comment by philn** [comment]
No i think it's due either to webgl2 or service-worker, now both enabled by default. `WebSWClientConnectionMessages.h` makes me think this is part of the latter.

**Comment by philn** [comment]
webgl2 and service-worker now disabled by default. They can be enabled in 2.22 recipe later on if needed.

**Comment by psaavedra** [comment]
Build passed : https://gitlab.com/saavedra.pablo/meta-perf-browser/pipelines/44137050

**Pull request merged**
