### PR TITLE
wpewebkit: Add Dispatch display refreshes earlier when skipping frames patch from WebKit bugzilla

### PR DESCRIPTION
**Pull request by psaavedra**
Issue: https://github.com/Igalia/meta-webkit/issues/373

### CODE REVIEW

**Comment by alexgcastro** [comment]
Thanks for handling this, I have 2 questions: did you check we get improvements with the patch in benchmarks (MotionMark)? And this patch is actually obsolete and we need to use the new ones in this bug and the one that depends on it:

https://bugs.webkit.org/show_bug.cgi?id=233312

That is why if you have any time and can help to check how is the current situation it would be helpful ;-), :pray:

**Comment by psaavedra** [comment]
> Thanks for handling this, I have 2 questions: did you check we get improvements with the patch in benchmarks (MotionMark)? And this patch is actually obsolete and we need to use the new ones in this bug and the one that depends on it:

Yes, I notice small changes are required for WEbKit on main but still applies find for 2.36(stable) where this patch is being applied here. 

Tested on several boards iMX6, rpi3 rpi4 (64 bits) the impact is consistent. The patch bost up the results of MotionMark tests. In particular Leaves and Images with improves the marks in x2 x5. E.g. those are the results before-after for the RPI3.


IMG_20220523_200524 (1)
IMG_20220523_201511 (1)


> 
> https://bugs.webkit.org/show_bug.cgi?id=233312
> 
> That is why if you have any time and can help to check how is the current situation it would be helpful ;-), pray

**Review by alexgcastro — APPROVED** [review]
LGTM!

**Comment by psaavedra** [comment]
After talk with @alexgcastro  @zdobersek  we agreed to keep waiting for a more revamped  version of the patch. There are some ideas for improving the patch but we still need to gather some more information.

**Pull request closed without merging**
