### PR TITLE
wpewebkit, webkitgtk: Bump to version 2.46.4

### PR DESCRIPTION
**Pull request by psaavedra**
WebKitGTK changes:
    
* Improve memory consumption and performance of Canvas getImageData.
* Fix preserve-3D intersection rendering.
* Fix video dimensions since GStreamer 1.24.9.
* Fix the HTTP-based remote Web Inspector not loading in Chromium.
* Fix content filters not working on about:blank iframes.
* Fix several crashes and rendering issues.

WPEWebKit 2.46.4 Changes:
    
* Improve memory consumption and performance of Canvas getImageData().
* Improve reliability and latency of audio/video MediaStream pipeplines.
* Improve detection of accelerated H.264 decoders.
* Add WebM audio capture bitrate configuration with GStreamer 1.24.9 and newer.
* Fix multi-touch input event handling.
* Fix getDisplayMedia() buffer format negotiation with PipeWire.
* Fix wrong video dimensions with GStreamer 1.34.9 and newer.
* Fix intersection and filter rendering for scenes with CSS transform-tyle: preserve-3d.
* Fix the HTTP-based remote Web Inspector not loading in Chromium.
* Fix Office 365 using an User-Agent quirk.
* Fix content filters not working on about:blank iframes.
* Fix logging in the memory pressure handler monitor.
* Fix the JSCOnly build with the GLib event loop enabled.
* Fix hole-punching media player when using fixed HTML body position.
* Fix the build with GCC 12.x when libwebrtc support is enabled.
* Fix the build with libsoup2.
* Fix several crashes and rendering issues.

Release Notes:
    
* https://webkitgtk.org/2024/11/27/webkitgtk2.46.4-released.html
* https://wpewebkit.org/release/wpewebkit-2.46.4.html

### CODE REVIEW

**Review by aperezdc — COMMENTED** [review]
I think it would be good to include [this revert as well](https://github.com/WebKit/WebKit/commit/7d076f98a13598cea187c6e489562b6d988af607) because it fixes an important performance regression, see [WebKit bug #283820](https://bugs.webkit.org/show_bug.cgi?id=283820) for the details.

The rest of the changes look fine 👌🏼

**Review by aperezdc — APPROVED** [review]
Patch LGTM 👍🏼

**Comment by psaavedra** [comment]
Job failed for Walnascar due to a recent icu update (https://git.openembedded.org/openembedded-core/commit/meta/recipes-support/icu?id=ef2bd18dd1db7e5f01db76889933bfdbb5415aaf). Fails on this job are acceptable since Walnascar is not yet released.

**Comment by psaavedra** [comment]
> Job failed for Walnascar due to a recent icu update (https://git.openembedded.org/openembedded-core/commit/meta/recipes-support/icu?id=ef2bd18dd1db7e5f01db76889933bfdbb5415aaf). Fails on this job are acceptable since Walnascar is not yet released.

Created issue https://github.com/Igalia/meta-webkit/issues/523.

**Pull request merged**
