### PR TITLE
Topic/use python3

### PR DESCRIPTION
**Pull request by Domarys**
Provide update for use of python3 class in compliance with OE-Core

### CODE REVIEW

**Comment by clopez** [comment]
> Provide update for use of python3 class in compliance with OE-Core

Which compliance is this? Does python2 support got removed or only deprecated? Any link to the policy or announcement?

I'm unsure if browserperfrunner works with python3, I prefer to leave it untouched until someone has the time to test it with all the plans it supports.

**Comment by otavio** [comment]
> > Provide update for use of python3 class in compliance with OE-Core
> 
> Which compliance is this? Does python2 support got removed or only deprecated? Any link to the policy or announcement?
> 
> I'm unsure if browserperfrunner works with python3, I prefer to leave it untouched until someone has the time to test it with all the plans it supports.

It was removed on master and as consequence of the upcoming April release.

**Comment by kraj** [comment]
> > Provide update for use of python3 class in compliance with OE-Core
> 
> Which compliance is this? Does python2 support got removed or only deprecated? Any link to the policy or announcement?
> 
> I'm unsure if browserperfrunner works with python3, I prefer to leave it untouched until someone has the time to test it with all the plans it supports.

yes it was announced few months ago at beginning of dev cycle for this relese

https://lists.yoctoproject.org/g/yocto/topic/removal_of_python_2_from/65216602?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,40,65216602

It would be better to bite the bullet now and make needed changes to make it work
with py3, another option is to depend on meta-python2 but that not first choice option

**Comment by otavio** [comment]
Using `meta-python2` is a step on the wrong direction. It is very likely that even using py3 it can be used on old branches and it also moves to the right direction.

**Comment by psaavedra** [comment]
I like the idea of to bump up this to python3 but simply is not going to work. We need to make changes in https://github.com/Igalia/browserperfrunner.git first. I just ran the 2to3 and I identified no few changes to do in the code (which many of then most be pushed to WK upstream as well):

```
RefactoringTool: Files that need to be modified:
RefactoringTool: ./webkitpy/benchmark_runner/benchmark_builder.py
RefactoringTool: ./webkitpy/benchmark_runner/benchmark_results.py
RefactoringTool: ./webkitpy/benchmark_runner/benchmark_results_unittest.py
RefactoringTool: ./webkitpy/benchmark_runner/benchmark_runner.py
RefactoringTool: ./webkitpy/benchmark_runner/run_benchmark.py
RefactoringTool: ./webkitpy/benchmark_runner/utils.py
RefactoringTool: ./webkitpy/benchmark_runner/webdriver_benchmark_runner.py
RefactoringTool: ./webkitpy/benchmark_runner/webserver_benchmark_runner.py
RefactoringTool: ./webkitpy/benchmark_runner/browser_driver/__init__.py
RefactoringTool: ./webkitpy/benchmark_runner/browser_driver/browser_driver_factory.py
RefactoringTool: ./webkitpy/benchmark_runner/browser_driver/linux_browser_driver.py
RefactoringTool: ./webkitpy/benchmark_runner/browser_driver/linux_chrome_driver.py
RefactoringTool: ./webkitpy/benchmark_runner/browser_driver/linux_cog_driver.py
RefactoringTool: ./webkitpy/benchmark_runner/browser_driver/linux_epiphany_driver.py
RefactoringTool: ./webkitpy/benchmark_runner/browser_driver/linux_firefox_driver.py
RefactoringTool: ./webkitpy/benchmark_runner/browser_driver/linux_minibrowsergtk_driver.py
RefactoringTool: ./webkitpy/benchmark_runner/browser_driver/linux_minibrowserwpe_driver.py
RefactoringTool: ./webkitpy/benchmark_runner/browser_driver/osx_browser_driver.py
RefactoringTool: ./webkitpy/benchmark_runner/browser_driver/osx_chrome_driver.py
RefactoringTool: ./webkitpy/benchmark_runner/browser_driver/osx_firefox_driver.py
RefactoringTool: ./webkitpy/benchmark_runner/browser_driver/osx_safari_driver.py
RefactoringTool: ./webkitpy/benchmark_runner/http_server_driver/__init__.py
RefactoringTool: ./webkitpy/benchmark_runner/http_server_driver/http_server_driver.py
RefactoringTool: ./webkitpy/benchmark_runner/http_server_driver/simple_http_server_driver.py
RefactoringTool: ./webkitpy/benchmark_runner/http_server_driver/http_server/twisted_http_server.py
RefactoringTool: ./webkitpy/browserperfdash/browserperfdash_runner.py
RefactoringTool: ./webkitpy/browserperfdash/browserperfdash_unittest.py
RefactoringTool: ./webkitpy/common/memoized.py
RefactoringTool: ./webkitpy/common/memoized_unittest.py
RefactoringTool: ./webkitpy/common/timeout_context.py
RefactoringTool: ./webkitpy/common/timeout_context_unittest.py
RefactoringTool: ./webkitpy/common/system/autoinstall.py
RefactoringTool: ./webkitpy/common/system/filesystem.py
RefactoringTool: ./webkitpy/common/system/filesystem_unittest.py
```

**Comment by psaavedra** [comment]
Created cross-reference issue in  `browserperfrunner`:   https://github.com/Igalia/browserperfrunner/issues/3

**Comment by clopez** [comment]
> Created cross-reference issue in `browserperfrunner`: [Igalia/browserperfrunner#3](https://github.com/Igalia/browserperfrunner/issues/3)

Thanks for checking.

I guess fixing that its going to take its time. In the meantime my suggestion is to not touch that recipe and instead add a note on the README saying that to build  browserperfrunner an optional dependency on the layer meta-python2 its needed (at least until Igalia/browserperfrunner#3 is fixed)

**Comment by otavio** [comment]
Yes, as a stopgap using `meta-python2` is acceptable.

**Comment by kraj** [comment]
> > Created cross-reference issue in `browserperfrunner`: [Igalia/browserperfrunner#3](https://github.com/Igalia/browserperfrunner/issues/3)
> 
> Thanks for checking.
> 
> I guess fixing that its going to take its time. In the meantime my suggestion is to not touch that recipe and instead add a note on the README saying that to build browserperfrunner an optional dependency on the layer meta-python2 its needed (at least until [Igalia/browserperfrunner#3](https://github.com/Igalia/browserperfrunner/issues/3) is fixed)

can we turn  browserperfrunner into a packageconfig and keep it disabled? that will
ensure that py2 is not a hard dependency

**Comment by clopez** [comment]
> can we turn browserperfrunner into a packageconfig and keep it disabled? that will
> ensure that py2 is not a hard dependency

The problem I'm getting is that I get a parse error.

```
ERROR: ParseError at /home/igalia/clopez/yocto/layers/meta-webkit/recipes-benchmark/browserperfrunner/browserperfrunner_git.bb:22: Could not inherit file classes/python-dir.bbclass 
```
How do you suggest to avoid this parse error  with a packageconfig option? Any code example?

**Comment by psaavedra** [comment]
> > can we turn browserperfrunner into a packageconfig and keep it disabled? that will
> > ensure that py2 is not a hard dependency
> 
> The problem I'm getting is that I get a parse error.
> 
> ```
> ERROR: ParseError at /home/igalia/clopez/yocto/layers/meta-webkit/recipes-benchmark/browserperfrunner/browserperfrunner_git.bb:22: Could not inherit file classes/python-dir.bbclass 
> ```
> 
> How do you suggest to avoid this parse error with a packageconfig option? Any code example?

On idea is to define a conditional `inherit` (https://www.yoctoproject.org/docs/2.3/bitbake-user-manual/bitbake-user-manual.html#inherit-directive). Something like this:

```
inherit ${@'python3-dir' if d.getVar("LAYERVERSION_core", True) > 11  else 'python-dir'}
```

**Comment by kraj** [comment]
> > can we turn browserperfrunner into a packageconfig and keep it disabled? that will
> > ensure that py2 is not a hard dependency
> 
> The problem I'm getting is that I get a parse error.
> 
> ```
> ERROR: ParseError at /home/igalia/clopez/yocto/layers/meta-webkit/recipes-benchmark/browserperfrunner/browserperfrunner_git.bb:22: Could not inherit file classes/python-dir.bbclass 
> ```
> 
> How do you suggest to avoid this parse error with a packageconfig option? Any code example?
```
inherit ${@bb.utils.contains("BBFILE_COLLECTIONS", "meta-python2", "python-dir", "python3-dir", d)}
```

**Comment by clopez** [comment]
> inherit ${@bb.utils.contains("BBFILE_COLLECTIONS", "meta-python2", "python-dir", "python3-dir", d)}

That will fail silently, since it would default to use python3-dir which is enough to build the recipe but not for running it.

I would like something that causes a build error for this recipe (instead of parse error) if meta-python2 its not added.

**Comment by clopez** [comment]
> inherit ${@'python3-dir' if d.getVar("LAYERVERSION_core", True) > 11  else 'python-dir'}

It seems LAYERVERSION_core is not what it suggests. The poky layer has the number 11 since 2017 in meta/conf/layer.conf

**Comment by kraj** [comment]
> > inherit ${@bb.utils.contains("BBFILE_COLLECTIONS", "meta-python2", "python-dir", "python3-dir", d)}
> 
> That will fail silently, since it would default to use python3-dir which is enough to build the recipe but not for running it.
> 
> I would like something that causes a build error for this recipe (instead of parse error) if meta-python2 its not added.

then try something like this

```
python() {
    if 'meta-python2' not in d.getVar('BBFILE_COLLECTIONS').split():
        raise bb.parse.SkipRecipe('Requires meta-python2 to be present.')
}
```

**Comment by psaavedra** [comment]
Another possibility could be just drop `browserperfrunner` from `meta-webkit`. Temporary ... at least .

WDYT?

**Comment by clopez** [comment]
I have this patch based on @kraj suggestions:

```diff
diff --git a/recipes-benchmark/browserperfrunner/browserperfrunner_git.bb b/recipes-benchmark/browserperfrunner/browserperfrunner_git.bb
index 70d5ef1..71e99ac 100644
--- a/recipes-benchmark/browserperfrunner/browserperfrunner_git.bb
+++ b/recipes-benchmark/browserperfrunner/browserperfrunner_git.bb
@@ -19,7 +19,17 @@ RDEPENDS_${PN} = " curl make patch perl procps psmisc python python-misc \
                    gobject-introspection python-pygobject gtk+3 ruby \
                    subversion libarchive-zip-perl"
 
-inherit python-dir
+# This recipe still requires python2.
+# So on Yocto dunfell and later its needed to use meta-python2
+# Port to python3 tracked at https://github.com/Igalia/browserperfrunner/issues/3
+inherit ${@bb.utils.contains("LAYERSERIES_CORENAMES", "dunfell", \
+               bb.utils.contains("BBFILE_COLLECTIONS", "meta-python2", "python-dir", "", d), \
+               "python-dir", d)}
+
+python() {
+    if d.getVar('LAYERSERIES_CORENAMES') == 'dunfell' and 'meta-python2' not in d.getVar('BBFILE_COLLECTIONS').split():
+        raise bb.parse.SkipRecipe('Requires meta-python2 to be present.')
+}
 
 do_install() {
     install -d ${D}${bindir}
```
I'm testing it and it seems to work:
* On dunfell it will not raise a parse error and will warn you that you need meta-python2 if you try to build this recipe
* On zeus it will work as before (no meta-python2 needed)

**Comment by clopez** [comment]
I will merge this, and I'm opening a new PR for the other patch

**Comment by psaavedra** [comment]
> I have this patch based on @kraj suggestions:
> 
> ```diff
> diff --git a/recipes-benchmark/browserperfrunner/browserperfrunner_git.bb b/recipes-benchmark/browserperfrunner/browserperfrunner_git.bb
> index 70d5ef1..71e99ac 100644
> --- a/recipes-benchmark/browserperfrunner/browserperfrunner_git.bb
> +++ b/recipes-benchmark/browserperfrunner/browserperfrunner_git.bb
> @@ -19,7 +19,17 @@ RDEPENDS_${PN} = " curl make patch perl procps psmisc python python-misc \
>                     gobject-introspection python-pygobject gtk+3 ruby \
>                     subversion libarchive-zip-perl"
>  
> -inherit python-dir
> +# This recipe still requires python2.
> +# So on Yocto dunfell and later its needed to use meta-python2
> +# Port to python3 tracked at https://github.com/Igalia/browserperfrunner/issues/3
> +inherit ${@bb.utils.contains("LAYERSERIES_CORENAMES", "dunfell", \
> +               bb.utils.contains("BBFILE_COLLECTIONS", "meta-python2", "python-dir", "", d), \
> +               "python-dir", d)}
> +
> +python() {
> +    if d.getVar('LAYERSERIES_CORENAMES') == 'dunfell' and 'meta-python2' not in d.getVar('BBFILE_COLLECTIONS').split():
> +        raise bb.parse.SkipRecipe('Requires meta-python2 to be present.')
> +}
>  
>  do_install() {
>      install -d ${D}${bindir}
> ```
> 
> I'm testing it and it seems to work:
> 
> * On dunfell it will not raise a parse error and will warn you that you need meta-python2 if you try to build this recipe
> * On zeus it will work as before (no meta-python2 needed)

I wonder if you could the `if` extensible to `>= dunfell`

**Comment by clopez** [comment]
> I wonder if you could the `if` extensible to `>= dunfell`

I would have to reverse the logic and check for all the old release names, as i don't know how the future ones would be named. I can try.

**Comment by otavio** [comment]
I think this is good enough for now. Has the py3 migration request been reported to `browserperfrunner` project upstream?

**Comment by clopez** [comment]
> I think this is good enough for now. Has the py3 migration request been reported to `browserperfrunner` project upstream?

We have reported https://github.com/Igalia/browserperfrunner/issues/3 to track this.
I'm right now unsure about the status of this project upstream (in the WebKit repo), maybe some of the fixes for python3 compatibility has been already done there and its a matter of importing a new snapshot. Has to be checked.

**Pull request merged**
