### PR TITLE
Libavif 0.11.1

### PR DESCRIPTION
**Pull request by jaskij**
Sorry for the bad commits, it was my first time using GitHub's web IDE.

This PR does three things with `libavif`:

- change `SRC_URI` to use git repo, not GH's source archives, which do not have a stable SHA (and trigger a Yocto warning)
- bump `libavif` to `0.11.1`
- what I believe to be a fix to `PACKAGECONFIG[dav1d]` which originally messed with `CMAKE_BUILD_TYPE` for whatever reason

### CODE REVIEW

**Comment by jaskij** [comment]
0.11.1 also seems to fix builds with clang, see #469

**Comment by clopez** [comment]
The commit fixing #469 is already integrated into libavif v0.10.0

So bumping it to the last stable release (v0.11.1) is enough.
Switching the build to use git instead of tarballs is not needed IMHO

**Comment by clopez** [comment]
> * change `SRC_URI` to use git repo, not GH's source archives, which do not have a stable SHA (and trigger a Yocto warning)

mmm.. missed this.

Do they trigger a Yocto warning? which Yocto version are you using?

**Comment by clopez** [comment]
I see it.. 

The tarballs from libavif at https://github.com/AOMediaCodec/libavif/releases/tag/v0.11.1 is automatically generated  from the release tag and not guaranteed to be byte-by-byte identical always

Related: https://github.com/orgs/community/discussions/46034

See this diffs:
1) https://github.com/containers/bubblewrap/releases/tag/v0.8.0
2) https://github.com/AOMediaCodec/libavif/releases/tag/v0.11.1

In 1 only 'bubblewrap-0.8.0.tar.xz' is guaranteed to be stable (you can see how it has the logo of a box and a size entry)
In 2 there are no stable assets

**Review by clopez — APPROVED** [review]
thanks!

**Comment by clopez** [comment]
> Also, I would love it if someone double checked the `LICENSE` entry - the first license, for `libavif` itself was BSD-2-Clause, but it includes some external projects with separate licenses.

Good point.

I just checked it: everything is BSD-2 except files from  apps/shared/iccjpeg.*  and files from android_jni/gradlew* 

The files for the first case are not built unless AVIF_BUILD_APPS=ON or AVIF_BUILD_TESTS=ON (the recipe here does not enable any of this options neither has a PACKAGECONFIG entry to allow doing that) and the files for the second case are android stuff which is also not used here.

**Pull request merged**
