### PR TITLE
Drop support for old Yocto release before kirkstone

### PR DESCRIPTION
**Pull request by psaavedra**
- Remove the support for dunfell, gatesgarth, hardknott and honister
- Update the CI repo manifest.xml documents
- Update the CI test jobs (nanbield is the main one to stress now)

### CODE REVIEW

**Review by manuelafm — APPROVED** [review]
LGTM but  there are some problems with tests, for example fetching sources... I think that some of them are transient errors, from what I remember.

**Comment by psaavedra** [comment]
Errors un scarthgap are not related with the meta-webkit components. Build fails on 'shadow-native'. Reported here: https://github.com/shadow-maint/shadow/issues/918

**Comment by psaavedra** [comment]
I've changed my mind. We will split this task in 2 steps. I will move forward this : https://github.com/Igalia/meta-webkit/pull/490 first (webkit bump-up) and I will delete this after the the release of the 2.44 release.

**Comment by psaavedra** [comment]
Closed in favour of https://github.com/Igalia/meta-webkit/pull/496

**Pull request closed without merging**
