### PR TITLE
Added wpewebkit version 2.24.0 and wpebackend 1.2.0

### PR DESCRIPTION
**Pull request by rpavelescu**

### CODE REVIEW

**Comment by philn** [comment]
Thanks, it looks good already but I can't merge this yet, because the updated libwpe 1.2.0 recipe is missing.
Another thing that would be great to fix is the git commit history. Your master branch has one merge commit and one commit containing the updated recipes. So here's a few guidelines to help keep the history clean, which is important when we need to track regressions with `git bisect`.

To avoid the merge commit here's what you can do in your master branch:

1. `git format patch -1` : This will save the "Added file..." commit in a patch file that you can reapply later
2. `git reset --hard HEAD^^`: This will remove the 2 commits on top of your branch, that's ok because you saved the important changes just before
3. `git pull origin master`: Download and apply the latest igalia/meta-webkit commits
4. `git am 0001-Added....patch`: Apply your local changes again

So now you would have only one commit to submit to the PR. You can do that with `git push -f <name-of-your-fork-remote> master`.

An alternative to consider before pushing, making one commit per modified recipe:
1. `git reset HEAD^`: undo the commit but keep the changed files in the tree
2. for each recipe: `git add <file>` and commit: `git commit -m "<recipe-name>: Update to version <number>"
3. Verify with `git log` that you have now 3 commits, and push `git push -f <name-of-your-fork-remote> master`

**Comment by philn** [comment]
As a general guideline, always keep your downstream branch up-to-date with upstream, `git rebase` is very helpful for this. And if git opens your editor asking for a merge commit, remove all the text from the editor buffer, save, exit, run `git merge --abort` and try to understand why a merge was requested, usually it means your branch history diverged from upstream, so a reorganization of your changes with `git rebase` might be needed.

**Comment by rpavelescu** [comment]
I reverted the changes from the merge. It should be okay now.

**Comment by philn** [comment]
Sorry, it's not. The revert added a new commit, which is not what we want, as I tried to explain above.

**Pull request merged**
