### PR TITLE
Backport recipes for Thud

### PR DESCRIPTION
**Pull request by philn**

### CODE REVIEW

**Comment by psaavedra** [comment]
Adding a new recipe for a new version has to come with the incorporation of a new CI job to test the build of the layer with that version. Something like what we did in this commit 4a2a32e but, in this case, avoiding the deletion of the job for the 2.28. In other case the CI will not check the build of the 2.32 recipes.

**Comment by philn** [comment]
I updated the CI, not sure how to test that though. :)

**Comment by psaavedra** [comment]
The CI should do it for you.

**Comment by psaavedra** [comment]
... here: https://gitlab.com/browsers/meta-webkit/-/jobs/1276717846


```
ERROR: Nothing PROVIDES 'vulkan-loader' (but /home/bot/yocto-webkit/sources/meta-gstreamer1.0/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.16.2.bb DEPENDS on or otherwise requires it). Close matches:
195  vulkan-demos
```

**Comment by philn** [comment]
Hum, looks like a meta-gstreamer bug, poky/thud has no vulkan-loader recipe it seems.

**Comment by philn** [comment]
Should be fixed now: https://github.com/OSSystems/meta-gstreamer1.0/pull/58

**Comment by philn** [comment]
It passed now? What happened? :)

**Comment by psaavedra** [comment]
> It passed now? What happened? :)

A wizard. No jokes. It seems the machine was overloaded because a parallel build. I just did a retry.

**Review by psaavedra — COMMENTED** [review]
I confess that I could be prone to add `DEFAULT_PREFERENCE = "-1"` in the newest recipes added in order to keep the default behavior. Note that Thud is nowadays  in EOL (latest release: 2.6.4 - October 2019) so this kind of updates in a active branch are quite exceptional.

Other than that. The MR LGTM.

**Comment by philn** [comment]
`DEFAULT_PREFERENCE` now set to `"-1"`.

**Review by psaavedra — APPROVED** [review]

**Comment by philn** [comment]
CI broke, wpewebkit couldn't find recent enough libwpe. I've pushed again, attempting to fix this.

**Comment by philn** [comment]
new CI round please ;)

**Pull request merged**
