### PR TITLE
Enable warrior builds

### PR DESCRIPTION
**Pull request by marhoy**

### CODE REVIEW

**Comment by philn** [comment]
Once https://github.com/Igalia/meta-webkit/pull/107 is merged only the warrior compat will be needed.

**Comment by psaavedra** [comment]
Please, resolve the conflict with #107 to approve and merge this one

**Comment by marhoy** [comment]
@psaavedra Conflict solved.

**Comment by philn** [comment]
Please rebase/squash all commits into a single one :)

**Comment by marhoy** [comment]
@philn Done

**Pull request merged**
