### PR TITLE
wpewebkit: Fix compilation error for armv7

### PR DESCRIPTION
**Pull request by dwrobel**
Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

### CODE REVIEW

**Comment by psaavedra** [comment]
Looks like this patch could be directly contributed in the webkit project. Did you already created a bug report in https://bugs.webkit.org/?

**Comment by kraj** [comment]
I think perhaps using llvm runtime when using clang might be a better option, it does not mean that this patch is not ok. This perhap s should be upstreamed. but maybe we should set

`RUNTIME = "llvm"`

which would automatically use llvm runtime with clang.

**Comment by dwrobel** [comment]
When I'm building it for DAC here https://github.com/stagingrdkm/meta-dac-sdk/blob/master/recipes-example/images/dac-image-igalia-cog.bb#L7-L12 I'm using `llvm` runtime. But that's not what should be set or hardcoded in `wpewebkit.bb`, I guess.

**Comment by clopez** [comment]
We don't like to carry downstream patches, so I think this is better reviewed upstream.
Please create a bug in https://bugs.webkit.org/ and upload the patch there. Select as category WPEWebKit.
Then link to the bug here.

**Comment by zdobersek** [comment]
References to the upstream fix:
https://bugs.webkit.org/show_bug.cgi?id=223916
https://trac.webkit.org/changeset/275285/webkit

**Comment by psaavedra** [comment]
The patch looks like the same @d If you can rebase and update the MR and add a reference to the upstream bugId  please.

**Comment by psaavedra** [comment]
This issue was fixed on upstream https://trac.webkit.org/changeset/275285/webkit

**Pull request closed without merging**
