### PR TITLE
Old recipe removal

### PR DESCRIPTION
**Pull request by zdobersek**

### CODE REVIEW

**Comment by philn** [comment]
Can you update the CI template too?

**Comment by philn** [comment]
https://gitlab.com/saavedra.pablo/meta-webkit/blob/master/.gitlab-ci.yml

**Comment by clopez** [comment]
Old recipes are kept there to make easier test with old versions in case you need that (helps when trying to find a regression or something like that).
For example, for webkitgtk we still have recipes going back to 2.8.5. It has helped me in several occasions to be able to quickly test old versions of webkitgtk by simply setting in local.conf ```PREFERRED_VERSION_webkitgtk = '$version'``` to test where something wrong started to happen.
Yocto by default picks the last version, I don't think deleting old ones is needed unless it is a burden for some reason

**Comment by psaavedra** [comment]
> Old recipes are kept there to make easier test with old versions in case you need that (helps when trying to find a regression or something like that).
> For example, for webkitgtk we still have recipes going back to 2.8.5. It has helped me in several occasions to be able to quickly test old versions of webkitgtk by simply setting in local.conf `PREFERRED_VERSION_webkitgtk = '$version'` to test where something wrong started to happen.
> Yocto by default picks the last version, I don't think deleting old ones is needed unless it is a burden for some reason

Those recipes will be still available in the release branches  (warrior, thud, sumo, rocko ... ).  I agree with to keep  the old recipes  as long as the corresponding CI  build task still compiles for the latest stable Yocto release (which should be the default env for the master branch in `meta-webkit`).

**Comment by clopez** [comment]
> Those recipes will be still available in the release branches (warrior, thud, sumo, rocko ... ). Anyway, I agree with to keep the old recipes as long as the corresponding CI build task still compiles for the latest stable Yocto release (which should be the default env for the master branch in `meta-webkit`).

Right. You have a good point.
On a second thought keeping old recipes doesn't add much value (and they are always there in the git history) and are largely untested (likely some of them not build anymore). Also it makes maybe harder to maintain the last recipes (since you have the `.inc `and several `.bb` files instead of just one `.bb `file) .
If you update this PR to apply again I'm fine with removing old recipes.

**Comment by psaavedra** [comment]
Should we agree to keep just the only the recipes for stable and oldstable +  dev ?

**Comment by psaavedra** [comment]
> Should we agree to keep just the only the recipes for stable and oldstable + dev ?

https://github.com/Igalia/meta-webkit/issues/162

**Comment by psaavedra** [comment]
I will close this PR. There is a new PR (https://github.com/Igalia/meta-webkit/pull/164) which address the very same issue according with what we agreed in https://github.com/Igalia/meta-webkit/issues/162.

**Pull request closed without merging**
